networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - grafana
    ports: 
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/data/:/var/lib/grafana/
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin